const whatsappMessages = [
  {
    "name": "Sahil",
    "message": "Hey, what's up?",
    "time": "10:30 AM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Aarav",
    "message": "Let's meet at 5 PM.",
    "time": "10:45 AM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Neha",
    "message": "Did you complete the assignment?",
    "time": "11:00 AM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Riya",
    "message": "Good morning! Have a great day 😊",
    "time": "8:00 AM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Vikram",
    "message": "I'm on my way.",
    "time": "12:15 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Simran",
    "message": "Call me when you're free.",
    "time": "1:00 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Rohan",
    "message": "Are you coming to the party?",
    "time": "9:30 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Ananya",
    "message": "I just sent you the notes.",
    "time": "5:20 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Kunal",
    "message": "Don't forget our meeting at 6.",
    "time": "3:45 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Meera",
    "message": "See you soon!",
    "time": "7:10 AM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Aditya",
    "message": "Where are you?",
    "time": "6:30 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Sanya",
    "message": "Happy Birthday! 🎉",
    "time": "12:00 AM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Nikhil",
    "message": "I'll be late today.",
    "time": "4:15 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Priya",
    "message": "Let’s go for coffee ☕",
    "time": "2:30 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Kabir",
    "message": "Send me the document.",
    "time": "11:40 AM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Aditi",
    "message": "Thanks for your help!",
    "time": "9:10 AM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Rahul",
    "message": "Let's plan a trip! 🌍",
    "time": "8:50 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Tanya",
    "message": "How was your day?",
    "time": "10:05 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
  {
    "name": "Manish",
    "message": "The match was amazing! 🏏",
    "time": "7:45 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=male",
  },
  {
    "name": "Pooja",
    "message": "Let's catch up soon!",
    "time": "4:55 PM",
    "profile_pic": "https://xsgames.co/randomusers/avatar.php?g=female",
  },
];

const chatMessages = [
  {"isMe": true, "message": "Hey! What's up?", "time": "10:30 AM"},
  {
    "isMe": false,
    "message": "Nothing much, just chilling. You?",
    "time": "10:32 AM",
  },
  {
    "isMe": true,
    "message": "Same here! Want to go out for coffee?",
    "time": "10:35 AM",
  },
  {"isMe": false, "message": "Sounds great! What time?", "time": "10:37 AM"},
  {"isMe": true, "message": "Let’s meet at 5 PM.", "time": "10:40 AM"},
  {"isMe": false, "message": "Perfect! See you then. 😊", "time": "10:42 AM"},
  {
    "isMe": true,
    "message": "By the way, did you finish the project?",
    "time": "11:00 AM",
  },
  {
    "isMe": false,
    "message": "Not yet, I’ll complete it by tonight.",
    "time": "11:05 AM",
  },
  {
    "isMe": true,
    "message": "Alright, let me know if you need any help!",
    "time": "11:10 AM",
  },
  {"isMe": false, "message": "Thanks, I will. 🙌", "time": "11:15 AM"},
  {"isMe": true, "message": "Okay, see you at 5!", "time": "11:20 AM"},
  {"isMe": false, "message": "Yep, see you! 👋", "time": "11:25 AM"},
  {
    "isMe": true,
    "message": "Did you watch the game last night?",
    "time": "11:35 AM",
  },
  {"isMe": false, "message": "Yeah! It was intense 🔥", "time": "11:37 AM"},
  {"isMe": true, "message": "That final goal was crazy!", "time": "11:39 AM"},
  {
    "isMe": false,
    "message": "Totally! I didn’t expect that.",
    "time": "11:40 AM",
  },
  {
    "isMe": true,
    "message": "Let’s plan a movie night soon.",
    "time": "11:43 AM",
  },
  {
    "isMe": false,
    "message": "Sounds awesome. This weekend?",
    "time": "11:45 AM",
  },
  {"isMe": true, "message": "Saturday night works!", "time": "11:48 AM"},
  {"isMe": false, "message": "Cool. I’ll bring popcorn 🍿", "time": "11:49 AM"},
  {"isMe": true, "message": "Can you send me that file?", "time": "11:51 AM"},
  {"isMe": false, "message": "Sure, give me a sec.", "time": "11:52 AM"},
  {
    "isMe": false,
    "message": "Sent it. Let me know if it opens.",
    "time": "11:53 AM",
  },
  {"isMe": true, "message": "Got it. Thanks!", "time": "11:55 AM"},
  {"isMe": false, "message": "Np. Anytime!", "time": "11:56 AM"},
  {
    "isMe": true,
    "message": "Do you want to study together?",
    "time": "12:00 PM",
  },
  {"isMe": false, "message": "Yeah, when are you free?", "time": "12:02 PM"},
  {"isMe": true, "message": "Let’s do 4 PM.", "time": "12:03 PM"},
  {"isMe": false, "message": "Cool. Library or cafe?", "time": "12:05 PM"},
  {"isMe": true, "message": "Library’s better.", "time": "12:06 PM"},
  {"isMe": false, "message": "Okay, see you there!", "time": "12:10 PM"},
  {"isMe": true, "message": "Did you eat something?", "time": "12:11 PM"},
  {
    "isMe": false,
    "message": "Not yet, gonna grab lunch soon.",
    "time": "12:12 PM",
  },
  {"isMe": true, "message": "Cool. Don’t skip meals!", "time": "12:15 PM"},
  {"isMe": false, "message": "Haha okay mom 😄", "time": "12:17 PM"},
  {"isMe": true, "message": "Did you check Insta?", "time": "12:20 PM"},
  {"isMe": false, "message": "Not yet, why?", "time": "12:21 PM"},
  {"isMe": true, "message": "I tagged you in a meme 😂", "time": "12:22 PM"},
  {"isMe": false, "message": "Haha I’ll check now!", "time": "12:23 PM"},
  {"isMe": true, "message": "Tell me your review 😅", "time": "12:24 PM"},
  {
    "isMe": false,
    "message": "Brooo that meme killed me 😭",
    "time": "12:25 PM",
  },
  {"isMe": true, "message": "Told you 😂", "time": "12:26 PM"},
  {"isMe": false, "message": "You free this evening?", "time": "12:30 PM"},
  {"isMe": true, "message": "Yeah, after 7.", "time": "12:32 PM"},
  {"isMe": false, "message": "Wanna go for a walk?", "time": "12:33 PM"},
  {"isMe": true, "message": "Sure, sounds good.", "time": "12:35 PM"},
  {"isMe": false, "message": "Bring your dog too!", "time": "12:36 PM"},
  {"isMe": true, "message": "Of course, he’ll love it.", "time": "12:37 PM"},
  {"isMe": false, "message": "What’s his name again?", "time": "12:38 PM"},
  {"isMe": true, "message": "Simba 🐶", "time": "12:39 PM"},
  {"isMe": false, "message": "Aww cute name!", "time": "12:40 PM"},
  {"isMe": true, "message": "Thanks 😄", "time": "12:42 PM"},
  {"isMe": false, "message": "Did you complete your task?", "time": "12:45 PM"},
  {"isMe": true, "message": "Almost done. Just polishing.", "time": "12:46 PM"},
  {"isMe": false, "message": "Good job! Keep it up.", "time": "12:48 PM"},
  {"isMe": true, "message": "Appreciate it!", "time": "12:50 PM"},
  {
    "isMe": false,
    "message": "Are you joining the meeting?",
    "time": "01:00 PM",
  },
  {"isMe": true, "message": "Yeah, logging in now.", "time": "01:01 PM"},
  {"isMe": false, "message": "Cool. Don’t be late 😅", "time": "01:02 PM"},
  {"isMe": true, "message": "I gotchu!", "time": "01:03 PM"},
  {"isMe": false, "message": "Lunch plans today?", "time": "01:05 PM"},
  {"isMe": true, "message": "Thinking Chinese. You in?", "time": "01:06 PM"},
  {"isMe": false, "message": "Always! 😋", "time": "01:07 PM"},
  {"isMe": true, "message": "Meet at 2?", "time": "01:10 PM"},
  {"isMe": false, "message": "Done ✅", "time": "01:11 PM"},
  {
    "isMe": true,
    "message": "Have you seen the new trailer?",
    "time": "01:15 PM",
  },
  {"isMe": false, "message": "YES! It’s fire 🔥", "time": "01:16 PM"},
  {"isMe": true, "message": "I can’t wait for the movie!", "time": "01:17 PM"},
  {"isMe": false, "message": "Me neither!!", "time": "01:18 PM"},
  {"isMe": true, "message": "Let’s book advance tickets?", "time": "01:20 PM"},
  {"isMe": false, "message": "Yess do it now!", "time": "01:21 PM"},
  {"isMe": true, "message": "Okay booking 3 seats.", "time": "01:22 PM"},
  {"isMe": false, "message": "Add Rahul too!", "time": "01:23 PM"},
  {"isMe": true, "message": "Noted ✅", "time": "01:24 PM"},
  {"isMe": false, "message": "Btw you free on Sunday?", "time": "01:30 PM"},
  {"isMe": true, "message": "Yeah why?", "time": "01:31 PM"},
  {"isMe": false, "message": "Picnic plan!", "time": "01:32 PM"},
  {"isMe": true, "message": "Omg yes count me in!", "time": "01:33 PM"},
  {"isMe": false, "message": "Cool. I’ll make the group.", "time": "01:34 PM"},
  {"isMe": true, "message": "Make sure to add Priya too!", "time": "01:35 PM"},
  {"isMe": false, "message": "Will do 👌", "time": "01:36 PM"},
  {"isMe": true, "message": "You bring the speakers?", "time": "01:40 PM"},
  {
    "isMe": false,
    "message": "Sure, I’ll charge them tonight.",
    "time": "01:42 PM",
  },
  {"isMe": true, "message": "Let’s vibe 🌞", "time": "01:43 PM"},
  {"isMe": false, "message": "It’s gonna be epic 🔥", "time": "01:44 PM"},
  {"isMe": true, "message": "Okay back to work now 😅", "time": "01:45 PM"},
  {"isMe": false, "message": "Same here. Ttyl!", "time": "01:46 PM"},
];
